spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/courseman
    username: root
  jackson:
    default-property-inclusion: non-null

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"

basePackage:
  com.hanu.domainfs.examples